default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: noticket_development

test:
  <<: *default
  database: noticket_test

production:
  <<: *default
  database: noticket_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
